/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Intefaz;

import Datos.Aulas;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import javax.swing.ImageIcon;

/**
 *
 * @author Gabriela y Rocío
 */
public class MapaForm extends javax.swing.JFrame {

    /**
     * Creates new form Mapa2
     */
    private Browser browser; //buffer al navegador: chrome
    private BrowserView view;
    
    public MapaForm() {
        //Quita barra de titulo
        this.setUndecorated(true);
        initComponents();
        googleMaps();
        setIconImage(new ImageIcon(getClass().getResource("marcador.png")).getImage());
    }
    
    public void googleMaps() {
        this.setTitle("Geolocalización Salas y Departamentos");// titulo
        browser = new Browser();//onjeto para que te cren las paginas en tu jframe
        browser.loadURL("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Proyecto Geolocalizacion\\src\\Intefaz\\mapas.html");
        view = new BrowserView(browser); //objeto para ver la pagina web en java
        this.panelMapa.add(view); //agregar la pagina al jframe
        this.setLocationRelativeTo(null); //centrar la pantalla
        this.setVisible(true);//hacer visible 
    }
    
    public void setMarcador(Aulas aula){
        String cx = String.valueOf(aula.getCoordenadaX());
        String cy = String.valueOf(aula.getCoordenadaY());
        String contenido = aula.getContenido();
        
        if (cx != null && cy != null && contenido != null){
            browser.executeJavaScript(
            "var marker;" +
            "        marker = new google.maps.Marker({" +
            "          position: new google.maps.LatLng(" + cx + ", " + cy + ")," +
            "          map: map" +
            "    });" +
            "     google.maps.event.addListener(marker, 'click', (function(marker) {" +
            "       return function() {" + 
            "        map.setZoom(32);" +
            "        map.setCenter(marker.getPosition());" +
            "        infowindow.setContent(\""+ contenido +"\");" +
            "        infowindow.open(map, marker);" +
            "      }" +
            "    })(marker));"
            );
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMapa = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Geolocalizacion de Salas y Departamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMapa.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelMapa;
    // End of variables declaration//GEN-END:variables
}
